// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCir8yc_B4T84KFsP1G7mUQMjtTc6Ri8',
    appId: '1:973754295773:android:c377b546ee55b0fb0a4234',
    messagingSenderId: '973754295773',
    projectId: 'songgpt-9e4dc',
    storageBucket: 'songgpt-9e4dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkc6oXl9dTB0v3HkJpi927VbKMvAFzAss',
    appId: '1:973754295773:ios:93d518e57927fe240a4234',
    messagingSenderId: '973754295773',
    projectId: 'songgpt-9e4dc',
    storageBucket: 'songgpt-9e4dc.appspot.com',
    androidClientId: '973754295773-024607ogv0ol83c68f3qqhmqum7egkcc.apps.googleusercontent.com',
    iosClientId: '973754295773-7hd9pj4809o6ps5cldlh9gtjrvk8a0pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.songgpt',
  );
}
